// <auto-generated />
using Anh105.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Anh105.Migrations
{
    [DbContext(typeof(AnhDBContext))]
    [Migration("20211215024153_Create_Table_TA105s")]
    partial class Create_Table_TA105s
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Anh105.Models.PersonsAnh", b =>
                {
                    b.Property<string>("PersonID")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PersonID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Anh105.Models.TA105", b =>
                {
                    b.Property<string>("TAid")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TAGener")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TAName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TAid");

                    b.ToTable("TA105s");
                });
#pragma warning restore 612, 618
        }
    }
}
